#!/bin/bash

if [ -e ~/LAMW ]; then
	if [ -e ~/LAMW/lamw4linux/lamw-install.log ]; then 
		cat ~/LAMW/lamw4linux/lamw-install.log | grep OLD_ANDROID_SDK
		if [ $? = 0 ]; then
			exit 0
		else
			exit 1
		fi
	else
		echo "bad  state instalation LAMW!"
		exit 1
	fi
else
	echo "Not Installed!" &>2
	exit 1
fi