#!/bin/bash
#-------------------------------------------------------------------------------------------------#
#Universidade federal de Mato Grosso (Alma Mater)
#Course: Science Computer
#Version: 0.4.5
#Date: 01/14/2022
#Description:The "lamw_manager" is part of the core of LAMW Manager. This script is a wrapper for "core/lamw-instal.sh"
#-------------------------------------------------------------------------------------------------#


#Get Directory of LAMW Manager Core
if [ -e "$PWD/lamw_manager" ] && [ ! -d "$PWD/lamw_manager" ]; then
	export LAMW_MGR_CORE="$PWD"
else
	export LAMW_MGR_CORE="$(realpath $(dirname $0))"
	[ $? != 0 ] && export LAMW_MGR_CORE="${0/%\/lamw_manager}" 
fi

source "$LAMW_MGR_CORE/core/headers/common-shell.sh"
source "$LAMW_MGR_CORE/core/headers/lamw_manager_headers"
source "$LAMW_MGR_CORE/core/settings-editor/root-lamw-settings-editor.sh"

GetInitialStatus(){

	tty | grep -i 'dev/pts/[0-9]' > /dev/null

	if [ ! -e "$LAMW_INSTALL_LOG" ] && [ $? = 0 ]; then 
		AUTO_START_LAMW4LINUX=1
	fi
}
GetLocalJavaHome(){
	local lamw4linux_env="$LAMW4LINUX_HOME/etc/environment"
	if [ -e $lamw4linux_env ]; then
		export JAVA_HOME=$(grep '^export JAVA_HOME' "$lamw4linux_env" | sed 's|export JAVA_HOME=||g')
	fi	
}
StopGradleDaemon(){
	if [ -e "$LAMW_INSTALL_LOG" ] ; then
		local gradle_version="$(grep '^GRADLE_VERSION' $LAMW_INSTALL_LOG | sed 's/GRADLE_VERSION=//g')"
		local gradle_path="$ROOT_LAMW/gradle-$gradle_version"
		GetLocalJavaHome
	fi

	if [ "$gradle_path" != "" ] && [ -e "$gradle_path" ]; then 
		
		ps ax |  grep gradle | grep $ROOT_LAMW &>/dev/null
		if [ $? = 0 ]; then 
			echo "Stopping Gradle Daemons, please wait..."  
			$gradle_path/bin/gradle --stop
		fi
	fi
}

#Del lamw-overrides
DelTempFiles(){ 
	[ -e $LAMW_MANAGER_LOCK ] &&  rm $LAMW_MANAGER_LOCK
}

#Check if $USER is a sudo member 
CheckUserIsSudo(){
	grep sudo /etc/group  | grep $USER > /dev/null 2>&1
	if [ $? != 0 ]; then 
		export USE_PKEXEC=1
	fi
}

CheckFlags(){
	newPtr ref_flag="$1"
	local flagFind=$2
	echo "$ARGS" | grep "$flagFind" > /dev/null
	if [ $? = 0 ]; then 
		export ref_flag=1
		export ARGS=${ARGS//$flagFind/} # remove todas as ocorrencias de DEBUG=1
	fi
}

#Check if DEBUG flag is set 
getBashCMD(){
	if [ $DEBUG = 1 ]; then
		export CALL_BASH="$CALL_BASH -x"
	fi
}

isSupportedPolkit(){
	local error_msg="${VERMELHO}Fatal error:${NORMAL} Cannot run on tty terminal!!"
	tty | grep 'pts/[0-9]'>/dev/null
}


setUseLamwManagerSetup(){
	if [ "$USE_SETUP" = "1" ];
	then 
		isSupportedPolkit
		local support_polkit=$?

		if [ $support_polkit = 0 ]; then 
			USE_PKEXEC=1
		fi

		LAMW_MANAGER_ENV+=("USE_SETUP=1")
	else
		LAMW_MANAGER_ENV+=("USE_SETUP=0")
	fi
}

CheckLocalRootLAMW(){
	if [ "$LOCAL_ROOT_LAMW" != "" ]; then
		setRootLAMW
	else 
		isVariabelDeclared LOCAL_ROOT_LAMW
		if [ $? = 0 ]; then
			echo "${VERMELHO}Fatal error: LOCAL_ROOT_LAMW is declared as empty!${NORMAL}"
			exit 1
		else 
			setRootLAMW
		fi
	fi

	LAMW_MANAGER_ENV+=(ROOT_LAMW=$ROOT_LAMW)
	LAMW4LINUX_HOME=$ROOT_LAMW/lamw4linux
	LAMW_INSTALL_LOG="$LAMW4LINUX_HOME/lamw-install.log"
}

RunAsSudo(){
	sudo -i env ${LAMW_MANAGER_ENV[@]} $CALL_BASH "$LAMW_MGR_INSTALL" $*
	export EXIT_STATUS=$?
}


#Run LAMW Manager as Police Kit
RunAsPolkit(){
	isSupportedPolkit
	if [ $?  = 0 ]; then 
		LAMW_MANAGER_ENV+=(DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY)
		pkexec  env ${LAMW_MANAGER_ENV[@]} $CALL_BASH  "$LAMW_MGR_INSTALL" $*
		export EXIT_STATUS=$?
	else
		echo $error_msg
		export EXIT_STATUS=$?
	fi
	
	[  $ENTER_TO_EXIT = 1 ] && echo "press enter to exit ..." && read
	

}

#get install status and exit
getStatus(){
	echo "$*" | grep "get-status" > /dev/null
	if [ $? = 0 ]; then 
		if [ -e "$LAMW_INSTALL_LOG" ]; then
			exit 0
		else
			exit 1
		fi
	fi
}
#Wrapper function to Run LAMW Manager
Run(){
	getStatus $*
	IsFileBusy lamw_manager $LAMW_MANAGER_LOCK
	exec 3>$LAMW_MANAGER_LOCK
	echo "" >&3
	getBashCMD
	setUseLamwManagerSetup
	if [ $USE_PKEXEC = 1 ] ; then
		RunAsPolkit $*
	else
		RunAsSudo $*
	fi
	exec 3>&-
}

#main function

autoStartLAMW4Linux(){

	if [ $EXIT_STATUS = 0 ] && [ $AUTO_START_LAMW4LINUX = 1 ] && [ -e $LAMW_INSTALL_LOG ];then
		echo "${NEGRITO}Please wait,starting LAMW4Linux IDE ...${NORMAL}"
		exec `which startlamw4linux`
	else
		exit $EXIT_STATUS
	fi
}

main(){
	
	IsUserRoot "lamw_manager"
	CheckFlags DEBUG "DEBUG=1"
	CheckFlags USE_PKEXEC "PKEXEC=1"
	CheckFlags ENTER_TO_EXIT "ENTER=1"
	CheckUserIsSudo
	CheckLocalRootLAMW
	GetInitialStatus
	StopGradleDaemon
	Run $ARGS
	DelTempFiles
	autoStartLAMW4Linux
}

main $*