#!/bin/bash
#!This script is a wraper to lamw-install.sh

export DEBUG=0
export ARGS="$*"

if  [  "$(whoami)" = "root" ] #impede que o script seja executado pelo root 
then
	echo "Error: this version  of LAMW4Linux was designed  to run without root priveleges" >&2 # >&2 is a file descriptor to /dev/stderror
	echo "Exiting ..."
	exit 1
fi
echo "$ARGS" | grep DEBUG=1 > /dev/null 
if [ $? = 0 ]; then
	export DEBUG=1;
	export ARGS=${ARGS//DEBUG=1/} # remove todas as ocorrencias de DEBUG=1
fi

echo "$USER" > /tmp/lamw-overrides.conf
if [ -e $PWD/lamw-install.sh ]; then
	if [ $DEBUG = 1 ]; then  
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash -x "$PWD/lamw-install.sh" ${ARGS}
	else
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash "$PWD/lamw-install.sh" $*
	fi
else
	export AUX_PATH=$0
	export AUX_PATH=${AUX_PATH%/lamw-manager*} #expansão de variavel que remove  lamw-manager (do final da string) restando a path
	if [ $DEBUG = 1 ]; then
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY -x bash "$AUX_PATH/lamw-install.sh" ${ARGS}
	else
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY bash "$AUX_PATH/lamw-install.sh" $*
	fi
fi

if [ -e /tmp/lamw-overrides.conf ]
then
	rm /tmp/lamw-overrides.conf
fi
echo "press enter to exit ...";read