#!/usr/bin/env bash
#-------------------------------------------------------------------------------------------------#
#Universidade federal de Mato Grosso (Alma Mater)
#Course: Science Computer
#Version: 0.6.2
#Date: 01/27/2024
#Description: This script generates compiles LAMW Manager source code into an executable installer.
#Note: This script requires makeself, read more in https://makeself.io/
#-------------------------------------------------------------------------------------------------#

source "../core/headers/common-shell.sh"



AUX=$PWD

LAMW_MANAGER_TMP_BUILD="/tmp/lamw_manager_build"
LAMW_MANAGER_INSTALLER="lamw_manager_setup.sh"
LAMW_MANAGER_INSTALLER_DEBUG="lamw_manager_setup_debug.sh"
LAMW_MANAGER_FINAL_INSTALLER="/tmp/$LAMW_MANAGER_INSTALLER"
START_LAMW_MANAGER_FILE='.start_lamw_manager'
BUILD_GUI=0
BUILD_DEBUG=0

START_LAMW_MANAGER_STR=(
	'#!/bin/bash'
	'#-------------------------------------------------------------------------------------------------#'
	'### THIS FILE IS AUTOMATICALLY CONFIGURED by LAMW Manager'
	'###ou may comment out this entry, but any other modifications may be lost.'
	'#Description: This script is a parser to lamw_manager_setup.run'
	'#This script remove  -- is a delimiter separating makeself arguments from internal scripts'
	'#Ref: https://makeself.io/'
	'#-------------------------------------------------------------------------------------------------#'
	''
	''
	"ARGS=\"\$*\""
	'ARGS=${ARGS/\-\-/}  #This is expansion that removes the first occurrence --. \-  is the escape of -'
	"export USE_SETUP=1" 
)

files=(
	"../core"
	"../docs"
	"../lamw_manager"	
	".start_lamw_manager"
	"../../Getting Started.txt"
)

CheckBuildFlag(){
	if [ $BUILD_GUI = 1 ]; then 
		files+=("../.gui/images")
		files+=("../.gui/LAMWManager")
		START_LAMW_MANAGER_FILE="LAMWManager"
	fi
}
BuildGUI(){
	if [ $BUILD_GUI = 0 ]; then
		return 
	fi

	export PATH=$PATH:~/lazarus
	cd ../.gui
	lazbuild --build-mode= LAMWManager.lpi
	cd $AUX
}


initLAMWBuild(){
	if [ ! -e $LAMW_MANAGER_TMP_BUILD ]
	then
		mkdir $LAMW_MANAGER_TMP_BUILD
	fi
	if [ "$1" = "" ]; then
		START_LAMW_MANAGER_STRF=(
			"${START_LAMW_MANAGER_STR[@]}"
			"exec ./lamw_manager \$ARGS")
	else
		START_LAMW_MANAGER_STRF=(
			"${START_LAMW_MANAGER_STR[@]}"
			"exec bash -x ./lamw_manager \$ARGS"
		)
	fi
	WriterFileln "$AUX/.start_lamw_manager" "START_LAMW_MANAGER_STRF"
	chmod +x "$AUX/.start_lamw_manager"
}
CopyFiles(){
	#copy directorys and files to LAMW_MANAGER_TMP_BUILD
	for((i=0;i<${#files[*]};i++))
	do 
		if [ -e "${files[i]}" ]; then
			if [ -d "${files[i]}" ]; then # if files[i] is a directory 
				cp  -r "${files[i]}" "$LAMW_MANAGER_TMP_BUILD"
			else
				cp  "${files[i]}" "$LAMW_MANAGER_TMP_BUILD"
			fi
		fi
	done
}

RemoveTmpFiles(){
	cd  "$AUX"
	local del_files=(
		"../.gui/LAMWManager"
		"../.gui/out.txt"
		"../.gui/err.txt"
		"../.gui/units/backup"
		"../.gui/backup"
		"../.gui/lib"
		"$AUX/$START_LAMW_MANAGER_FILE" 
		"$AUX/.start_lamw_manager"
		"$LAMW_MANAGER_TMP_BUILD"
	)

	for((i=0;i<${#del_files[*]};i++))
	do
		if [ -d ${del_files[i]} ]; then rm_args='-rf'; fi
		if [ -e ${del_files[i]} ]; then 
			rm ${del_files[i]} $rm_args
		fi
	done
}
setBuildMode(){
	if [ $BUILD_DEBUG = 0 ]; then
		initLAMWBuild ""
	else
		output_lamw_manager_setup="$LAMW_MANAGER_INSTALLER_DEBUG"
		initLAMWBuild "2"
	fi
}
main(){
	local output_lamw_manager_setup="$LAMW_MANAGER_INSTALLER"
	
	if ! which makeself > /dev/null; then
		echo "${VERMELHO}Error${NORMAL}:Need install makeself!"
		echo "Use command: ${VERDE}sudo apt-get install makeself -y${NORMAL}"
		exit 1
	fi
	
	CheckBuildFlag 
	BuildGUI
	setBuildMode "$1"
	CopyFiles
	changeDirectory $LAMW_MANAGER_TMP_BUILD
	makeself --quiet --xz --copy --target '$HOME/lamw_manager' "$PWD" "$output_lamw_manager_setup"  "LAMW Manager Setup" "./${START_LAMW_MANAGER_FILE}"
	chmod +x $output_lamw_manager_setup
	cp $LAMW_MANAGER_TMP_BUILD/$output_lamw_manager_setup /tmp
	RemoveTmpFiles
}

case "$1" in
	"--gui")
		BUILD_GUI=1
	;;
	"--debug"|"debug")
		BUILD_DEBUG=1
	;;
esac

main 