#!/bin/bash
#-------------------------------------------------------------------------------------------------#
#Universidade federal de Mato Grosso (Alma Mater)
#Course: Science Computer
#Version  0.3.3
#Date: 10/15/2019
#Description: This script generates compiles LAMW Manager source code into an executable installer.
#Note: This script requires makeself, read more in https://makeself.io/
#-------------------------------------------------------------------------------------------------#

source "../core/common-shell.sh"


AUX=$PWD

LAMW_MANAGER_TMP_BUILD="/tmp/lamw_manager_build"
LAMW_MANAGER_INSTALLER="lamw_manager_setup.sh"
LAMW_MANAGER_FINAL_INSTALLER="$LAMW_MANAGER_TMP_BUILD/$LAMW_MANAGER_INSTALLER"
START_LAMW_MANAGER_FILE='.start_lamw_manager'
BUILD_GUI=0

START_LAMW_MANAGER_STR=(
	'#!/bin/bash'
	'#-------------------------------------------------------------------------------------------------#'
	'### THIS FILE IS AUTOMATICALLY CONFIGURED by LAMW Manager'
	'###ou may comment out this entry, but any other modifications may be lost.'
	'#Description: This script is a parser to lamw_manager_setup.run'
	'#This script remove  -- is a delimiter separating makeself arguments from internal scripts'
	'#Ref: https://makeself.io/'
	'#-------------------------------------------------------------------------------------------------#'
	''
	''
	"ARGS=\"\$*\""
	'ARGS=${ARGS/\-\-/}  #This is expansion that removes the first occurrence --. \-  is the escape of -'
	"./lamw_manager \$ARGS"
)

files=(
	"../core"
	"../docs"
	"../lamw_manager"	
	".start_lamw_manager"
	"../../Getting Started.txt"
)

CheckBuildFlag(){
	if [ $BUILD_GUI = 1 ]; then 
		files[${#files[*]}]="../.gui/images"
		files[${#files[*]}]="../.gui/LAMWManager"
		START_LAMW_MANAGER_FILE="LAMWManager"
	fi
}
BuildGUI(){
	export PATH=$PATH:~/lazarus
	cd ../.gui
	lazbuild --build-mode= LAMWManager.lpi
	cd $AUX
}
CleanBuilGUI(){
	cd ../.gui

	local files=(
		'LAMWManager'
		'out.txt'
		'units/backup'
		lib/x86_64-linux/{LAMWManager.compiled,LAMWManager.or,uglobal.o,umain.lfm,umain.ppu,uprocessos.ppu,uproxy.o,LAMWManager.o,LAMWManager.res,uglobal.ppu,umain.o,uprocessos.o,uproxy.lfm,uproxy.ppu}
	)

	for((i=0;i<${#files[*]};i++))
	do
		if [ -d ${files[i]} ]; then
			rm_args='-rf'
		fi
		if [ -e ${files[i]} ]; then 
			rm ${files[i]} $rm_args
		fi
	done
}
WriterFileln "$AUX/.start_lamw_manager" "START_LAMW_MANAGER_STR"
chmod +x "$AUX/.start_lamw_manager"
CheckBuildFlag
qt=${#files[*]}



if [ ! -e $LAMW_MANAGER_TMP_BUILD ]
then
	mkdir $LAMW_MANAGER_TMP_BUILD
fi
BuildGUI
#copy directorys and files to LAMW_MANAGER_TMP_BUILD
for((i=0;i<qt;i++))
do 
	if [ -e "${files[i]}" ]; then
		if [ -d "${files[i]}" ]; then # if files[i] is a directory 
			cp  -r "${files[i]}" "$LAMW_MANAGER_TMP_BUILD"
		else
			cp  "${files[i]}" "$LAMW_MANAGER_TMP_BUILD"
		fi
	fi
done

CleanBuilGUI
changeDirectory $LAMW_MANAGER_TMP_BUILD
makeself  --quiet --xz --copy --target '$HOME/lamw_manager' $PWD $LAMW_MANAGER_INSTALLER "LAMW Manager Setup" "./${START_LAMW_MANAGER_FILE}"
cp "$LAMW_MANAGER_FINAL_INSTALLER" "$AUX"

changeDirectory $AUX
if [ -e $LAMW_MANAGER_TMP_BUILD ]; then
	rm -r $LAMW_MANAGER_TMP_BUILD
fi

#Remove tempfile
if [ -e "$AUX/$START_LAMW_MANAGER_FILE" ]; then
	rm "$AUX/$START_LAMW_MANAGER_FILE"
fi
