#!/bin/bash
#-------------------------------------------------------------------------------------------------#
#Universidade federal de Mato Grosso (Alma Mater)
#Course: Science Computer
#Version: 0.4.0
#Date: 06/12/2021
#Description: The "lamw_headers" is part of the core of LAMW Manager. This script contains LAMW Manager variables.
#-------------------------------------------------------------------------------------------------#
#						Section Version 
#------------------------------------------------------------------------------------------
LAMW_INSTALL_VERSION="0.4.0.3"
JDK_VERSION=8
FPC_LAZ_VERSION="2.0.12"
FPC_VERSION="3.2.0"	
FPC_TRUNK_VERSION="3.2.2"
LAZARUS_STABLE_VERSION="2.0.12"
ANT_VERSION_STABLE='1.10.11'
CMD_SDK_TOOLS_VERSION="4.0"
FPC_TRUNK_SVNTAG="release_${FPC_TRUNK_VERSION//\./_}"
LAZARUS_STABLE="lazarus_"${LAZARUS_STABLE_VERSION//\./_} #expansão que remove todos '.' por _, obs '\.' barra invertida escapa '.'

OLD_GRADLE=(
	$ROOT_LAMW/gradle-{"6.1.1","4.10.3","4.4.1"}
)
OLD_ANT=(
	$ROOT_LAMW/apache-ant-1.10.{8,7,5}
)

OLD_FPC_SOURCES=(
	"$LAMW4LINUX_HOME/fpcsrc"
	$LAMW4LINUX_HOME/usr/share/fpcsrc/{trunk,fixes_3_2,release_3_2_0}
)

OLD_FPC_STABLE=(
	$LAMW4LINUX_HOME/usr/local/lib/fpc/3.0.4
	$LAMW4LINUX_HOME/usr/lib/fpc/$FPC_VERSION
)

OLD_LAZARUS_STABLE_VERSION=(
	2.0.{10..2..2}
	"1.8.4"
)

OLD_LAMW_INSTALL_VERSION=(
	0.4.0{.{2,1},}
	0.3.6{.{2,1},}
	0.3.{5,4}{r1,}
	"0.3.3r2"
	"0.3."{3..0}
	"0.2.1"		
)
#------------------------------------------------------------------------------------------	
export ANDROID_HOME=$ROOT_LAMW
export ANDROID_SDK_ROOT=$ANDROID_HOME/sdk
export ARM_ANDROID_TOOLS="$ANDROID_SDK_ROOT/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin"
export AARCH64_ANDROID_TOOLS="$ANDROID_SDK_ROOT/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin"
export LLVM_ANDROID_TOOLCHAINS="$ANDROID_SDK_ROOT/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin"
export JAVA_HOME="$ROOT_LAMW/jdk/zulu-$JDK_VERSION"
export PATH=$JAVA_HOME/bin:$PATH:$LLVM_ANDROID_TOOLCHAINS
export XDG_DATA_DIRS="/usr/share:/usr/local/share:$LAMW_USER_HOME/.local/share"

#------------------------------------------------------------------------------------------


#						Section URL
#------------------------------------------------------------------------------------------

CMD_SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip"
LAMW_SRC_LNK="https://github.com/jmpessoa/lazandroidmodulewizard.git"
FPC_DEB_LINK="https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%20${FPC_LAZ_VERSION}/fpc-laz_${FPC_VERSION}-1_amd64.deb"
ANT_TAR_URL="https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION_STABLE}-bin.tar.xz"
LAZARUS_STABLE_SRC_LNK="https://svn.freepascal.org/svn/lazarus/tags/${LAZARUS_STABLE}"
LAMW_PACKAGE_URL="https://raw.githubusercontent.com/jmpessoa/lazandroidmodulewizard/master/package.json"
ZULU_API_JDK_URL="https://api.azul.com/zulu/download/community/v1.0/bundles/"
ZULU_API_JDK_URL+="?java_version$JDK_VERSION&jdk_version=$JDK_VERSION&zulu_version=$JDK_VERSION&os=linux&arch=x86&hw_bitness=64&ext=tar.gz&bundle_type=jdk&javafx=false&latest=true&support_term=lts"
FPC_TRUNK_URL="https://svn.freepascal.org/svn/fpc/tags/${FPC_TRUNK_SVNTAG}"

#------------------------------------------------------------------------------------------	
CMD_SDK_TOOLS_ZIP="commandlinetools-linux-7302050_latest.zip"
CMD_SDK_TOOLS_DIR="$ANDROID_SDK_ROOT/cmdline-tools"
SDK_LICENSES_PARAMETERS=(--licenses )

ANT_TAR_FILE="apache-ant-${ANT_VERSION_STABLE}-bin.tar.xz"
ANT_HOME="$ROOT_LAMW/apache-ant-${ANT_VERSION_STABLE}"
GRADLE_CFG_HOME="$LAMW_USER_HOME/.gradle"
OLD_FPC_CFG_PATH="$LAMW_USER_HOME/.fpc.cfg"
FPC_CFG_PATH="$LAMW_USER_HOME/.fpc.cfg"
FPC_LIB_PATH="$LAMW4LINUX_HOME/usr/local/lib/fpc/${FPC_VERSION}"
FPC_MKCFG_EXE="$LAMW4LINUX_HOME/usr/local/bin/fpcmkcfg"

FPC_DEB="fpc-laz_${FPC_VERSION}-1_amd64.deb"
FPC_CROSS_ARM_DEFAULT_PARAMETERS=('clean crossall crossinstall  CPU_TARGET=arm OS_TARGET=android OPT="-dFPC_ARMHF" SUBARCH="armv7a" INSTALL_PREFIX=/usr')

LAMW_PACKAGES=(
	"$ROOT_LAMW/lazandroidmodulewizard/android_bridges/tfpandroidbridge_pack.lpk"
	"$ROOT_LAMW/lazandroidmodulewizard/android_wizard/lazandroidwizardpack.lpk"
	"$ROOT_LAMW/lazandroidmodulewizard/ide_tools/amw_ide_tools.lpk"
	"$ROOT_LAMW/lazandroidmodulewizard/fcl_bridges/fcl_bridges_pack.lpk"
)


LIBS_ANDROID="libx11-dev libgtk2.0-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev libxtst-dev libatk1.0-dev libghc-x11-dev freeglut3 freeglut3-dev "
PROG_TOOLS="menu git subversion make build-essential zip unzip android-tools-adb gdb wget jq "

FPC_TRUNK_SOURCE_PATH="$LAMW4LINUX_HOME/usr/share/fpcsrc"

LAMW_INSTALL_WELCOME=(
	"${NEGRITO}LAMW Manager v$LAMW_INSTALL_VERSION${NORMAL}\n"
)

LAMW_LINUX_SPP=(
	"\t*Debian 10\n"
	"\t*Ubuntu 18.04 LTS\n"
)


