.\" Manpage for lamw_manager
.TH lamw_manager 8 "2021 Jun 17 " "0.4.0" "LAMW manager man page"
.SH NAME
lamw_manager -\ manager to LAMW framework
.SH SINOPSIS
\fBenv LOCAL_ROOT_LAMW=[dir]\fR ./lamw_manager
.br
\fBenv LOCAL_ROOT_LAMW=[dir]\fR ./lamw_manager   [\fBACTION\fR] [\fBOPTIONS\fR]
.br
lamw_manager
.br
 ./lamw_manager 	[\fBACTION\fR] [\fBOPTIONS\fR]
.br 
 ./lamw_manager 	[\fBOPTIONS\fR]
.br
 ./lamw_manager 	[\fBACTIONS\fR][\fBOPTIONS\fR] DEBUG=1
.br
 ./lamw_manager 	[\fBuninstall\fR] [\fB\-\-reset\fR] [\fB\-\-reset-aapis\fR]
 			 	[\fB\-\-sdkmanager\fR] [\fB\-\-update-lamw\fR] [\fB\-\-help\fR]
.SH DESCRIPTION
LAMW Manager is a command line tool,like APT, to automate the installation, configuration and upgrade the framework 
\.br
LAMW - Lazarus Android Module Wizard
.SH INSTALLING LAMW ON CUSTOM DIRECTORY
To install LAMW environment on custom directory you need use \fBenv LOCAL_ROOT_LAMW=path_your_directory\fR ./lamw_manager  [\fBACTION\fR] [\fBOPTIONS\fR]
.br
sample:
.br
\fBenv LOCAL_ROOT_LAMW=/opt/LAMW\fR ./lamw_manager

.SH ACTIONS
\fBuninstall\fR 		Clean all LAMW
.SH OPTIONS
\fB\-\-reset\fR  			Clean and Install LAMW
.br
\fB\-\-reset-aapis\fR   	Reset Android API's to default
.br
\fB\-\-help\fR   			Show this help
.br
\fB\-\-sdkmanager\fR  		Run Android SDK Manager
.br
\fB\-\-update\-lamw\fR  	Just upgrade LAMW Framework(with the latest version avaliable in git)
.SH PROXY OPTIONS
lamw_manager [ACTIONS]||[OPTIONS] \fB\-\-use-proxy\fR \fB\-\-server\fR [HOST] \fB\-\-port\fR [NUMBER]
.br
sample:
.br
 ./lamw_manager --update-lamw --use-proxy --server 10.0.16.1 --port 3128
.SH DEBUG
 Use the \fBDEBUG=1\fR flag later in any position of ./lamw_manager (flag does not count as argument)
.br
 \fBsample\fR:
.br
 ./lamw_manager --reset \fBDEBUG=1\fR
.br
 ./lamw_manager \fBDEBUG=1\fR --reset
.SH BUGS
	¹	Fail! Folder /platforms is empty! Use command ./lamw_manager \fB\-\-reset-aapis\fR to fix this error.
.br
	²	If the LAMW4Linux launcher does not appear in the start menu, simply restart the user session.
.br
	³	You can launch LAMW4Linux with command: \fBstartlamw4linux\fR .
.SH AUTHOR
Daniel Oliveira 

